### ISSUE TITLE
@aws-sdk/lib-storage - fs, stream resolution in browser

### ISSUE THREAD

**Issue by glynd** [aws/aws-sdk-js-v3#1688]
**Describe the bug**
Trying to use this in a browser (Angular) test app and getting missing dependencies (appear to be nodejs components)

```console
Error: ./node_modules/@aws-sdk/lib-storage/dist/es/utils/bytelength.js
Module not found: Error: Can't resolve 'fs' in '/XXXXXXXXXXX/node_modules/@aws-sdk/lib-storage/dist/es/utils'

Error: ./node_modules/@aws-sdk/lib-storage/dist/es/data-chunk/yield-chunk.js
Module not found: Error: Can't resolve 'stream' in '/XXXXXXXXXXX/node_modules/@aws-sdk/lib-storage/dist/es/data-chunk'
```

**SDK version number**

1.0.0-rc.6

**Is the issue in the browser/Node.js/ReactNative?**
Browser

**Details of the browser/Node.js/ReactNative version**
  Browsers:
    Chrome: 86.0.4240.198
    Safari: 14.0.1

**To Reproduce (observed behavior)**

I suspect there are easier ways to reproduce... but this will do.

Run:

```consle
ng new uploaderbug
cd uploaderbug
npm i @aws-sdk/lib-storage

edit src/app/app.component.ts 
to:

8<----------8<----------8<----------8<----------8<----------8<----------
import { Component } from '@angular/core';

import * as S3 from '@aws-sdk/client-s3';
import * as LibStorage from '@aws-sdk/lib-storage';


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'uploadbug';

  private dummyfunc() {

     const s3Client = new S3.S3Client({region: "eu-west-1"});

     const target :S3.PutObjectCommandInput = {Bucket: "dummybucket", Key: "dummykey"};

     const fileUpload = new LibStorage.Upload({client: s3Client, params: target});

  }
}
8<----------8<----------8<----------8<----------8<----------8<----------
```

Run:
ng serve

Result as above

**Expected behaviour**
Not expecting dependencies of nodejs components - is it currently not browser compatible?

**Screenshots**

**Additional context**
Didn't see any issues like this using the v2 Javascript SDK

**Comment by alexforsyth** [comment]
Interesting, this should be compatible with browsers. Investigating

**Comment by alexforsyth** [comment]
Yep, looks like this is an issue with on the browser. Prioritizing fixing this

**Comment by G-Rath** [comment]
Ironically this is also the case the other way around: projects that don't have the `dom` lib (i.e, node scripts, aws lambdas, etc - things not in the browser) will error on the S3 client due to `ReadableStream` & `Blob`.

**Comment by Schwusch** [comment]
I had the issue @G-Rath described, and my workaround was to add `dom` to my `tsconfig.json`:
```json
{
  "compilerOptions": {
    "lib": [
      "dom"
    ]
}
```

**Comment by G-Rath** [comment]
You can avoid needing to enable the `DOM` lib by defining the interfaces yourself:

```
// @aws-sdk/client-s3 references these DOM lib interfaces,
// so we need them to exist to compile without having DOM.
declare global {
  /* eslint-disable @typescript-eslint/no-empty-interface */
  interface Blob {}
  interface ReadableStream {}
  /* eslint-enable @typescript-eslint/no-empty-interface */
}
```

This could be done in the library itself to remove the need to include `DOM` :)

**Comment by alexforsyth** [comment]
The stream and fs resolutions should be fixed in this PR: https://github.com/aws/aws-sdk-js-v3/pull/2039.

Following up with what @G-Rath said, we're not going to be doing something like:
```
// @aws-sdk/client-s3 references these DOM lib interfaces,
// so we need them to exist to compile without having DOM.
declare global {
  /* eslint-disable @typescript-eslint/no-empty-interface */
  interface Blob {}
  interface ReadableStream {}
  /* eslint-enable @typescript-eslint/no-empty-interface */
}
```

Because this isn't a complete fix (s3, lambda, etc). While I agree that adding dom to tsconfig is probably a bit sucky, I think this is the best path forward for the mean time.

```
{
  "compilerOptions": {
    "lib": [
      "dom"
    ]
}
```

**Comment by G-Rath** [comment]
> Because this isn't a complete fix (s3, lambda, etc).

I'm not sure what you mean by this? You should be able to include this in any client that uses a global interface and call it a day - because its an empty interface there's no risk of causing any conflicts nor changing existing code to account for properties not existing (because they will all still exist).

This will work both for global interfaces being sourced from the `DOM` lib, and from those coming from `@types/node`.

**Comment by andrejunges** [comment]
still getting this on `v3.6.1`, any suggestions?

**Comment by alexforsyth** [comment]
@andrejunges you'll need to include dom types.

**Comment by andrejunges** [comment]
@alexforsyth  I have it there. I can still see the warning though.
