### ISSUE TITLE
Bundling for Lambda requires unnecessary dependencies

### ISSUE THREAD

**Issue by perpil** [aws/aws-sdk-js-v3#5516]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

For Lambda coldstarts, it is well known creating a minified, tree-shaken bundle measurably improves performance vs. using the V3 JavaScript SDK version bundled with Lambda.  

| coldstart time (ms) | bundled/minified |
| ------------ | ------ |
| 675        | no|
| 241       | yes|

In a minified bundle, if you use any AWS client, `credential-provider-node` starts pulling in `client-sso` and other packages. These packages are unused but add > 32KB to the minified bundle.  If you set the `credentials` parameter for the AWS client, it still pulls in `client-sso` and can't be tree-shaken out. Since loading credentials from environment variables is what most developers need for Lambda, there should be a way to only bundle the `credential-provider-env` credentials provider.  Arguably this should be the default in the Lambda environment.

### SDK version number

@aws-sdk/client-sts@3.454.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v20.9.0

### Reproduction Steps

1. Create a lambda with any AWS client, i.e. STS:
  ```javascript
  import { GetCallerIdentityCommand, STSClient } from '@aws-sdk/client-sts';

  const stsClient = new STSClient({region: process.env.AWS_REGION});

  export async function handler(event, context) {
    const result = await stsClient.send(new GetCallerIdentityCommand({}));
    return {
      statusCode: 200,
      body: JSON.stringify({
        result
      }),
      headers: {
        'Content-Type': 'application/json',
      },
    };
  }
  ```
2. Minify, treeshake and create metafile with esbuild. If you use [NodeJsFunction](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs.NodejsFunction.html) in the CDK your bundling looks like: 
```javascript
  bundling: {
        metafile: true, //use https://esbuild.github.io/analyze/ to analyze the bundle
        minify: true,
        treeshake: true,
        target: 'esnext',
        format: 'esm',
        platform: 'node',
        mainFields: ['module', 'main'],
        outputFileExtension: '.mjs',
        externalModules: [],
        banner:
          "const require = (await import('node:module')).createRequire(import.meta.url);const __filename = (await import('node:url')).fileURLToPath(import.meta.url);const __dirname = (await import('node:path')).dirname(__filename);",
  }
```
3. Review the metafile using the [esbuild analyzer](https://esbuild.github.io/analyze/) and note it includes packages like `client-sso`
   I've attached the metafile for the above so you can directly review it: [index.meta.json](https://github.com/aws/aws-sdk-js-v3/files/13443531/index.meta.json)
   Look at it in Flamechart mode and note the inclusion of these packages: `client-sso`, `token-providers`, `credential-provider-sso`
   Screenshot of why `token-providers` is not tree-shaken: <img width="788" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/97474956/67bcf49a-79d5-490a-bb60-62a0f7a57258">

### Observed Behavior

The packages `client-sso`, `token-providers` and `credential-provider-sso` get bundled unnecessarily and can't be tree-shaken out.

### Expected Behavior

Either it uses `credential-provider-env`, or client config has some way of allowing me to omit `credential-provider-node` so the unnecessary packages can be tree-shaken out.

**Comment by perpil** [comment]
When I replaced the compiled version of [this file](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/credential-provider-node/src/defaultProvider.ts) with the contents below in my minified bundle, the sso code treeshook out and I saw a 41KB reduction in bundle size and a 39 ms reduction in cold start time: 

```javascript
import { fromEnv } from '@aws-sdk/credential-provider-env';
import {
  chain,
  CredentialsProviderError,
  memoize,
} from '@smithy/property-provider';
export const defaultProvider = (init = {}) =>
  memoize(
    chain(...[fromEnv()], async () => {
      throw new CredentialsProviderError(
        'Could not load credentials from any providers',
        false
      );
    }),
    (credentials) =>
      credentials.expiration !== undefined &&
      credentials.expiration.getTime() - Date.now() < 300000,
    (credentials) => credentials.expiration !== undefined
  );
```

I suspect the impact to coldstart will be even greater if I use the sdk bundled with the lambda, but just patch that file.  I did do a test where I minified everything but used what was on disk for `client-sso`, `token-providers` and `credential-provider-sso` and saw a 270 ms impact.

**Comment by RanVaknin** [comment]
Hi @perpil ,

Thanks for the reproduction. I can confirm the observed behavior. I'll discuss it with the team and get back to you.

All the best,
Ran~

**Comment by RanVaknin** [comment]
Hi @perpil ,

After discussing this with the team I got some more context about this. 

We provide the entire credential provider chain so that the SDK code deployed can be platform agnostic, whether it runs on EC2, Lambda, EKS etc, it should just work. Since the bundling process happens prior to the deployment part, the bundler cannot know which platform its bundling for and so omitting the unnecessary providers is not possible.

You can probably use something like [Yarn Patch](https://yarnpkg.com/cli/patch), but I cannot officially recommend it. 

Regarding this part 

>The impact to coldstart is even greater if I use the sdk which is included on disk by the Lambda runtime. I have done a test where I minified everything but used what was on disk for client-sso, token-providers and credential-provider-sso and saw a 270-335 ms impact.

Using the SDK provided by lambda is going to be less optimized because it fits an even greater array of use cases. Cold start times are in fact lower when bundling and minifying as shown in [our own benchmarking](https://aws.amazon.com/blogs/developer/reduce-lambda-cold-start-times-migrate-to-aws-sdk-for-javascript-v3/).

Currently there is no way / plan to fix this. 
Thank you for taking the time to raise the feature request, and I hope that this does not discourage you from engaging with us in the future.

All the best,
Ran~

**Comment by perpil** [comment]
Hi @RanVaknin 

I understand the general purpose nature of the provider and the fact that bundling is not aware of the target platform.  I am also aware that I can patch the provider myself and am successfully doing so using patch-package.  The key point is that this is slowing down coldstarts for a large cross section of users (everyone using the V3 SDK and Lambda).  The Lambda team would need to take incredible engineering effort to reduce coldstarts by 39 ms whereas making a change to the SDK comes at a much lower cost.  There are multiple ways of solving this without breaking support for other platforms and maintaining backwards compatibility.

1. Lazy loading.  Since fromEnv is one of the first in the chain, there is no need to load other providers if there is a hit. https://aaronstuyvenberg.com/posts/lambda-lazy-loading
2. Lazy loading based on environment variables.  Either setting an environment variable for different behavior or autodetecting based on the presence of lambda specific environment variables.
3. Allowing the developer to specify a custom provider as config that completely overrides the provider being used.

Any of these options would be better than what we have.  I encourage you to reach out to former Lambda principal David Yanacek or current principal Nik Pinski before making a final decision.  I spoke to both of them at re:invent and they understand the positives that reducing the cold start for everyone would have.  It may seem small for the SDK team, but would be a big win for the Lambda team.

**Comment by RanVaknin** [comment]
Hi @perpil,

Thank you for your patience. 

@kuhe is working on implementing lazy loading of credential providers and we hope that the changes will get rolled into the next SDK version provided by lambda but we don't have any specific timeline at the moment.

Thanks again for your contribution.
All the best,
Ran~

**Comment by kuhe** [comment]
@perpil in https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.499.0, we released dynamic imports (lazy loading) for the node credential chain providers. 

SSO and other credential providers including their dependency clients will not be loaded if you resolve to ENV credentials or otherwise pass credentials directly to a client. If you use Webpack for Node.js apps with the SDK, these dynamic imports will be split into other chunks and not loaded unless necessary.

At this time it is not available on AWS Lambda unless you bundle in or upload the `node_modules/@aws-sdk` and `node_modules/@smithy` parts of your application.

**Comment by perpil** [comment]
Thanks for the update.  I'm using esbuild and bundling.  I modified my [repro](https://github.com/perpil/sso-coldstart-benchmark-cdk) to use 3.499 so you can see the behavior yourself.  I'm expecting the delta between me hand patching the defaultProvider to only include `fromEnv` and the lazy loaded chain in 3.499 to be closer in time, but I'm still seeing ~27ms difference.  When I omit the SSO packages from the bundle so it uses the version on disk for lambda, I see an even higher latency of 312ms.  This leads me to believe that for some reason, the SSO stuff is still getting loaded.  I'll keep digging to see if I can figure out exactly what is going on.

> SSO and other credential providers including their dependency clients will not be loaded if you resolve to ENV credentials or otherwise pass credentials directly to a client.

I don't think this is currently true. As an experiment I tried setting both `credentials` and `defaultCredentialProvider` to the `fromEnv()` provider when I instantiate the STSClient.  It seems it loads the defaultProvider regardless due to this code: https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-sts/src/runtimeConfig.ts#L7 Due to whatever is going on above, I think it is still loading the SSO client.

> At this time it is not available on AWS Lambda unless you bundle in or upload the node_modules/@aws-sdk and node_modules/@smithy parts of your application.

Yep understood I'm bundling it.

**Comment by perpil** [comment]
I've tracked down what is still loading the SSO client.  It's `@aws-sdk/credential-provider-ini`.  If you comment out lines 7 and 53-55 in [this file](https://github.com/aws/aws-sdk-js-v3/blob/0b29652616c4c5b0fed896157538432d502e31a8/packages/credential-provider-ini/src/resolveProfileData.ts#L7) the SSO client is no longer loaded and latency is normal.  It's not clear to me why the SSO bits are loaded (but unused) even when credentials-provider-ini is lazy loaded in the default provider.

The way to see this in my repro is:

1. [Make the SSO packages external](https://github.com/perpil/sso-coldstart-benchmark-cdk#loading-sso-from-disk)
2. [Run a cold start](https://github.com/perpil/sso-coldstart-benchmark-cdk#running-a-coldstart)

When you look in the logs, you'll see an Init Duration of >400ms.  

To remove the SSO impact:

1. Open `node_modules/@aws-sdk/credential-provider-ini/dist-es/resolveProfileData.js`, comment out lines 7 and 53-55 and save it.
2. `cdk synth;cdk deploy` 
3. hit the url 
 
You'll see an Init Duration closer to ~200ms.

Rule of thumb, if you see an Init Duration >400 ms it's loading SSO, if it's closer to 200 it isn't.  By making the SSO packages external, they are loaded from disk so the latency hit is very apparent in the Init Duration logs.

**Comment by kuhe** [comment]
We can check what is loaded by logging the require.cache. 

We have additional updates pending to defer both the providers and the underlying clients used by providers, such as SSO, STS, SSO OIDC.

**Comment by kuhe** [comment]
https://github.com/aws/aws-sdk-js-v3/pull/5681 contains a second phase of implementing deferred loading.

**Comment by kuhe** [comment]
> need to mark packages as external

This shouldn't be necessary. With the introduction of async imports, bundlers should generate the unused code into separate chunks that are never loaded. If you don't mark e.g. `@aws-sdk/credential-provider-sso` as external, it appears in your root chunk?

**Comment by perpil** [comment]
I'm using esbuild, you can see my config [here](https://github.com/perpil/sso-coldstart-benchmark-cdk/blob/aa32e9b421b4ae93eeface168d6a19147e572448/lib/coldstart-benchmark-stack.mjs#L27) Let me turn on [splitting](https://esbuild.github.io/api/#splitting) and see what happens.

**Comment by kuhe** [comment]
I see, it's not supported at the same level as in webpack. In that case marking external for esbuild is a good way to induce the splitting.

**Comment by perpil** [comment]
I tried using splitting, but it appears incompatible with the CDK esbuild wrapper which is always setting `outfile`.

Adding:

```
esbuildArgs: {
          '--splitting': true,
}
```
results in: 

`✘ [ERROR] Must use "outdir" when code splitting is enabled`

And adding:

```
esbuildArgs: {
          '--splitting': true,
          '--outdir': node_modules
}
```

results in:

`✘ [ERROR] Cannot use both "outfile" and "outdir"`
